# Data Exploratory

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset_mood_smartphone.csv", sep=",").drop(columns=["Unnamed: 0"])
df.head()

        id                     time variable  value
0  AS14.01  2014-02-26 13:00:00.000     mood    6.0
1  AS14.01  2014-02-26 15:00:00.000     mood    6.0
2  AS14.01  2014-02-26 18:00:00.000     mood    6.0
3  AS14.01  2014-02-26 21:00:00.000     mood    7.0
4  AS14.01  2014-02-27 09:00:00.000     mood    6.0

In [3]:
print(df['id'].nunique())
print(df['id'].value_counts())

27
id
AS14.01    21999
AS14.23    21852
AS14.13    19592
AS14.28    19276
AS14.06    18092
AS14.29    17499
AS14.12    17311
AS14.30    17279
AS14.26    16403
AS14.33    16390
AS14.07    16045
AS14.17    15826
AS14.05    15745
AS14.02    14581
AS14.27    14575
AS14.24    14430
AS14.03    14425
AS14.25    12589
AS14.31    11889
AS14.19    11397
AS14.32    11193
AS14.09    10886
AS14.14     9286
AS14.08     7902
AS14.16     3982
AS14.20     3620
AS14.15     2848
Name: count, dtype: int64

Some rows in unnamed is removed!

In [4]:
df['variable'].value_counts()

variable
screen                  96578
appCat.builtin          91288
appCat.communication    74276
appCat.entertainment    27125
activity                22965
appCat.social           19145
appCat.other             7650
circumplex.arousal       5643
circumplex.valence       5643
appCat.office            5642
mood                     5641
call                     5239
appCat.travel            2846
appCat.utilities         2487
sms                      1798
appCat.finance            939
appCat.unknown            939
appCat.game               813
appCat.weather            255
Name: count, dtype: int64

In [5]:
df[df.variable=='sms']['value'].value_counts()

value
1.0    1798
Name: count, dtype: int64

In [6]:
df[df.variable=='call']['value'].value_counts()

value
1.0    5239
Name: count, dtype: int64

In [7]:
df.describe()

               value
count  376710.000000
mean       40.665313
std       273.726007
min    -82798.871000
25%         2.025000
50%         7.029000
75%        29.356000
max     33960.246000

In [8]:
df['timestamp'] = pd.to_datetime(df['time'])
df['date'] = df['timestamp'].dt.date
df['hour'] = df['timestamp'].dt.hour

In [12]:
df.head()

,id,time,variable,value,timestamp,date,hour
0,AS14.01,2014-02-26 13:00:00.000,mood,6.0,2014-02-26 13:00:00,2014-02-26,13
1,AS14.01,2014-02-26 15:00:00.000,mood,6.0,2014-02-26 15:00:00,2014-02-26,15
2,AS14.01,2014-02-26 18:00:00.000,mood,6.0,2014-02-26 18:00:00,2014-02-26,18
3,AS14.01,2014-02-26 21:00:00.000,mood,7.0,2014-02-26 21:00:00,2014-02-26,21
4,AS14.01,2014-02-27 09:00:00.000,mood,6.0,2014-02-27 09:00:00,2014-02-27,9

In [ ]:
agg_dict = {
    'mood': ['mean', 'std'],
    'circumplex.arousal': ['mean'],
    'circumplex.valence': ['mean'],
    'activity': ['mean', 'std'],
    'screen': ['sum'],
    'call': ['sum'],
    'sms': ['sum'],
}

# Add all app categories as sum
app_cols = [col for col in df['variable'].unique() if 'appCat' in col]
for col in app_cols:
    agg_dict[col] = ['sum']

print(agg_dict)

df_pivot = df.pivot_table(
    index=['id', 'date'],
    columns='variable',
    values='value',
    aggfunc=agg_dict,
).reset_index()

{'mood': ['mean', 'std'], 'circumplex.arousal': ['mean'], 'circumplex.valence': ['mean'], 'activity': ['mean', 'std'], 'screen': ['sum'], 'call': ['sum'], 'sms': ['sum'], 'appCat.builtin': ['sum'], 'appCat.communication': ['sum'], 'appCat.entertainment': ['sum'], 'appCat.finance': ['sum'], 'appCat.game': ['sum'], 'appCat.office': ['sum'], 'appCat.other': ['sum'], 'appCat.social': ['sum'], 'appCat.travel': ['sum'], 'appCat.unknown': ['sum'], 'appCat.utilities': ['sum'], 'appCat.weather': ['sum']}

In [15]:
df_pivot.head()

variable,id,date,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,...,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,circumplex.arousal,circumplex.valence,mood,screen,sms
0,AS14.01,2014-02-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,AS14.01,2014-02-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,AS14.01,2014-02-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
3,AS14.01,2014-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
4,AS14.01,2014-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [16]:
# how many na values are there in each column of
df_pivot.isna().sum()

variable
id                         0
date                       0
activity                 785
appCat.builtin           778
appCat.communication     790
appCat.entertainment    1123
appCat.finance          1766
appCat.game             1780
appCat.office           1697
appCat.other             853
appCat.social            985
appCat.travel           1544
appCat.unknown          1709
appCat.utilities        1540
appCat.weather          1860
call                     635
circumplex.arousal       705
circumplex.valence       707
mood                     705
screen                   766
sms                     1239
dtype: int64

In [17]:
df['variable'].value_counts()

variable
screen                  96578
appCat.builtin          91288
appCat.communication    74276
appCat.entertainment    27125
activity                22965
appCat.social           19145
appCat.other             7650
circumplex.arousal       5643
circumplex.valence       5643
appCat.office            5642
mood                     5641
call                     5239
appCat.travel            2846
appCat.utilities         2487
sms                      1798
appCat.finance            939
appCat.unknown            939
appCat.game               813
appCat.weather            255
Name: count, dtype: int64

In [18]:
df[df['variable'] == 'activity']['value'].value_counts()

value
0.000000    9835
0.008333     465
0.033333     371
0.016667     370
0.025000     364
            ...
0.126214       1
0.412281       1
0.170940       1
0.620968       1
0.731092       1
Name: count, Length: 1868, dtype: int64

In [19]:
df_pivot['activity'].describe()

count    1188.000000
mean        0.120003
std         0.098301
min         0.000000
25%         0.054872
50%         0.095634
75%         0.149358
max         0.566171
Name: activity, dtype: float64

In [20]:
df_pivot = df_pivot.sort_values(['id', 'date'])

# Forward fill per user
df_pivot = df_pivot.groupby('id').ffill()

# Fill remaining NaNs
df_pivot = df_pivot.fillna(0)

In [22]:
df_pivot.head()

variable,date,activity,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,appCat.office,appCat.other,appCat.social,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,circumplex.arousal,circumplex.valence,mood,screen,sms
0,2014-02-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2014-02-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2014-02-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,2014-02-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,2014-02-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [23]:
df_pivot['mood'].value_counts()

mood
0.000000    642
7.000000    243
7.200000    100
8.000000     82
6.800000     81
7.400000     73
7.600000     68
6.400000     62
6.600000     60
7.800000     59
6.000000     56
7.500000     49
6.200000     44
7.250000     44
6.500000     37
6.750000     33
6.333333     28
7.750000     24
6.250000     20
5.500000     15
8.200000     13
7.666667     13
5.800000     13
6.666667     10
7.333333      9
5.400000      8
5.750000      7
9.000000      7
8.250000      7
8.400000      7
5.000000      6
5.600000      6
5.666667      4
8.600000      4
8.500000      4
5.200000      3
6.833333      3
3.750000      2
5.250000      2
3.500000      2
4.800000      2
8.800000      2
8.333333      2
4.500000      1
4.400000      1
5.333333      1
4.333333      1
4.750000      1
3.800000      1
3.000000      1
3.333333      1
7.166667      1
8.166667      1
7.833333      1
6.166667      1
4.666667      1
8.750000      1
9.333333      1
8.666667      1
5.833333      1
Name: count, dtype: int64

In [26]:
lags = [1, 2, 3, 7]

for lag in lags:
    df[f'mood_lag_{lag}'] = df.groupby('id')['mood_mean'].shift(lag)
    df[f'activity_lag_{lag}'] = df.groupby('id')['activity_mean'].shift(lag)
    df[f'screen_lag_{lag}'] = df.groupby('id')['screen_sum'].shift(lag)

KeyError: 'Column not found: mood_mean'