# Data Exploratory

In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("dataset_mood_smartphone.csv", sep=",")
df.head()

   Unnamed: 0       id                     time variable  value
0           1  AS14.01  2014-02-26 13:00:00.000     mood    6.0
1           2  AS14.01  2014-02-26 15:00:00.000     mood    6.0
2           3  AS14.01  2014-02-26 18:00:00.000     mood    6.0
3           4  AS14.01  2014-02-26 21:00:00.000     mood    7.0
4           5  AS14.01  2014-02-27 09:00:00.000     mood    6.0

In [16]:
df

        Unnamed: 0       id                     time        variable   value
0                1  AS14.01  2014-02-26 13:00:00.000            mood   6.000
1                2  AS14.01  2014-02-26 15:00:00.000            mood   6.000
2                3  AS14.01  2014-02-26 18:00:00.000            mood   6.000
3                4  AS14.01  2014-02-26 21:00:00.000            mood   7.000
4                5  AS14.01  2014-02-27 09:00:00.000            mood   6.000
...            ...      ...                      ...             ...     ...
376907     2770399  AS14.30  2014-04-11 07:51:16.948  appCat.weather   8.032
376908     2772465  AS14.30  2014-04-19 11:00:32.747  appCat.weather   3.008
376909     2774026  AS14.30  2014-04-26 10:19:07.434  appCat.weather   7.026
376910     2774133  AS14.30  2014-04-27 00:44:48.450  appCat.weather  23.033
376911     2784435  AS14.32  2014-04-07 18:25:14.036  appCat.weather  22.431

[376912 rows x 5 columns]

Some rows in unnamed is removed!

In [18]:
df['variable'].value_counts()

variable
screen                  96578
appCat.builtin          91288
appCat.communication    74276
appCat.entertainment    27125
activity                22965
appCat.social           19145
appCat.other             7650
circumplex.valence       5643
circumplex.arousal       5643
appCat.office            5642
mood                     5641
call                     5239
appCat.travel            2846
appCat.utilities         2487
sms                      1798
appCat.finance            939
appCat.unknown            939
appCat.game               813
appCat.weather            255
Name: count, dtype: int64

In [15]:
df[df.variable=='sms']['value'].value_counts()

value
1.0    1798
Name: count, dtype: int64

In [17]:
df[df.variable=='call']['value'].value_counts()

value
1.0    5239
Name: count, dtype: int64

In [9]:
df.describe()

         Unnamed: 0          value
count  3.769120e+05  376710.000000
mean   4.501273e+05      40.665313
std    5.411519e+05     273.726007
min    1.000000e+00  -82798.871000
25%    9.422875e+04       2.025000
50%    2.274385e+05       7.029000
75%    5.160412e+05      29.356000
max    1.427711e+07   33960.246000